modLoader = "javafml" #mandatory
loaderVersion = "[44,)"
license = "MIT"
[[mods]] #mandatory
modId = "stweaks" #mandatory
version = "${version}" #mandatory
displayName = "Sistr'sTweaks" #mandatory
#updateJSONURL="http://myurl.me/" #optional
#displayURL="http://example.com/" #optional
logoFile = "icon.png" #optional
#credits="Thanks for this example mod goes to Java" #optional
authors = "Sistr" #optional

description = '''
ゲームバランスを調整するModです。
'''

[[dependencies.stweaks]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[44,)" #mandatory
ordering = "NONE"
side = "BOTH"

[[dependencies.stweaks]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.3,1.20)"
ordering = "NONE"
side = "BOTH"
